# This is an example configuration file
# To learn more, see the full config.yaml reference: https://docs.continue.dev/reference

name: Local Config2
version: 1.0.0

models:
  - name: Qwen
    provider: ollama
    model: qwen2.5:14b

    roles:
      - chat
      - edit
      - apply